### ISSUE TITLE
[USABILIDAD] Arma inicial no equipada visualmente.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#102]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción**: Tu arma inicial no aparece equipada en tu inventario de manera visual pero tu 
personaje la lleva equipada y la podrá utilizarla 
**Pasos para reproducirlo**: Iniciar una partida y abrir el inventario para ver que esa arma no se 
encuentra equipada.

**Comment by dakeXd** [comment]
Arma inicial agregada a la interfaz
