### ISSUE TITLE
[ESTÉTICA] Los esqueletos no tienen animación.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#106]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC/Móvil, Chrome/Firefox 
**Descripción**: Los esqueletos se mueven desplazándose por el nivel sin ninguna animación.
**Pasos para reproducirlo**: Iniciar una partida donde aparezcan los enemigos esqueletos

**Comment by dakeXd** [comment]
Animaciones Agregadas!
