### ISSUE TITLE
[ESTÉTICA] Carencia de slider de sonido.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#107]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción**: Solo hay una slider que controla la música y nada controla los sonidos. 
**Pasos para reproducirlo**: Iniciar el juego y dirigirte al menú de ajustes

**Comment by sourdonny** [comment]
Se ha implementado un slider para los efectos sonoros del juego.
