### ISSUE TITLE
[ESTÉTICA] Fallo en la slider de sonidos.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#108]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción**: Si se baja el slider de música al mínimo, los sonidos de los enemigos se siguen 
escuchando. 
**Pasos para reproducirlo:** Bajar el volumen de la música en el menú de ajustes e iniciar una partida 
para escuchar los enemigos.

**Comment by sourdonny** [comment]
Nueva barra para los efectos de sonidos, incluidos los enemigos.
