### ISSUE TITLE
[PROGRAMACIÓN] Abrir menú de pausa al morir.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#109]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción**: Una vez haz muerto puedes pulsar el menú de pausa.
**Pasos para reproducirlo**: Morir y pulsar la tecla escape para activar el menú de pausa.

**Comment by dakeXd** [comment]
Eliminada la posibilidad de abrir el menu de pausa mientras el menu de muerte este activo
