### ISSUE TITLE
[ESTÉTICA] Slider sin texturizar.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#110]
Prioridad: Bajo 
Plataforma o entorno: PC/Móvil, Chrome/Firefox 
Descripción: El slider de la música no tiene texturas y no se adecua a la estética del juego 
Pasos para reproducirlo: Ir al menú de ajustes

**Comment by sourdonny** [comment]
Arreglada estética del slider
