### ISSUE TITLE
[USABILIDAD] Falta de curas.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#118]
Prioridad: Media
Plataforma o entorno: PC/Móvil, Chrome/Firefox
Descripción: Sería necesario algún sistema de curación para facilitar el juego.
Pasos para reproducirlo: 
1. Entrar en partida. 
2. Moverse por el escenario o cambiar de sala.

**Comment by sourdonny** [comment]
Se ha implementado el sistema de bendiciones, cartas que dan curación al jugador
