### ISSUE TITLE
[USABILIDAD] Falta de claridad de estadísticas.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#121]
Prioridad: Media
Plataforma o entorno: PC, Móvil
Descripción: Las estadísticas de los objetos no son claras.
Pasos para reproducirlo:
1. Entrar en partida. 
2. Conseguir objetos. 
3. Pulsar “Q” para ver las estadísticas.

**Comment by sourdonny** [comment]
Las estadísticas de los objetos se especifican más claramente en la parte de arriba de las cartas.
