### ISSUE TITLE
[USABILIDAD] Sistema de elementos confuso.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#123]
Prioridad: Media
Plataforma o entorno: PC, Chrome/Firefox
Descripción: El sistema de elementos no se entiende, puesto que falta algo de información en la 
guía.
Pasos para reproducirlo:

**Comment by sourdonny** [comment]
En la guía se ha puesto una página con los elementos y su efectividad entre ellos.
