### ISSUE TITLE
[PROGRAMACIÓN] Bloqueo de juego al reintentar con menú de pausa activo.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#127]
Prioridad: Alto
Plataforma o entorno: PC, Chrome/Firefox
Descripción: Al reiniciar la partida, si se pulsa el botón con el menú de pausa activo, este queda 
bloqueado, dejando solo disponible el botón Q. Esto se puede “solucionar” pulsando la tecla de 
escape de nuevo para abrir el menú de pausa.
Pasos para reproducirlo: 
1. Entrar en partida. 
2. Avanzar a la primera sala. 
3. Dejarse morir. 
4. Abrir el menú de pausa una vez haya aparecido el menú de “Fin de juego”. 
5. Pulsar “Reintentar”.

**Comment by rox06io** [comment]
![image](https://user-images.githubusercontent.com/72705329/143315454-f8252706-a982-4915-8710-190cbe325773.png)

**Comment by dakeXd** [comment]
Eliminada la posibilidad de abrir el menu de pausa cuando el jugador esta muerto
