### ISSUE TITLE
[USABILIDAD] No hay información de los enemigos que quedan fuera de los límites de visión del jugador.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#129]
**Prioridad**: Alto
**Plataforma o entorno:** PC, Chrome
**Descripción**: Sobre todo en el caso del jefe, cuando este se teletransporta a otro lugar y es fuera del 
campo de visión del jugador, puede causar mucha confusión puesto que este no sabe desde dónde 
le está atacando.
**Pasos para reproducirlo:** 
1. Entrar en partida. 
2. Avanzar por las salas y tratar de dejar enemigos fuera de la cámara.

**Comment by dakeXd** [comment]
Se ha añadido un trail al jefe para poder seguirle aunque salga de la visión del jugador
