### ISSUE TITLE
[PROGRAMACIÓN] Los enemigos no te causan daño en ciertas situaciones.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#130]
**Prioridad:** Alto
**Plataforma o entorno:** PC, Chrome
**Descripción**: Los enemigos, tras golpearte una vez, si siguen chocando contigo, no te causarán 
ningún daño. 
**Pasos para reproducirlo:** 
1. Entrar en partida. 
2. Avanzar a la primera sala para enfrentarte a un enemigo. 
3. Tras aparecer el enemigo, pegarte a él y dejar que te golpee una vez.

**Comment by dakeXd** [comment]
Ajustado el daño para que se ejecute en un intervalo mientras esten chocando contigo en vez  de solo al chocarse
