### ISSUE TITLE
[PROGRAMACIÓN] Canvas no ajustado al rotar la pantalla en móvil.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#131]
Prioridad: Alto
Plataforma o entorno: Móvil, Firefox
Descripción: La aplicación queda iniciada en vertical y, una vez es rotada a horizontal, el canvas no 
queda ajustado de nuevo a la nueva resolución, llegando a cortar algunos elementos de la pantalla.
Pasos para reproducirlo: 
1. Ejecutar el juego. 
2. Una vez quede rotada en vertical, volver a rotar a horizontal
![image](https://user-images.githubusercontent.com/72705329/143315638-94942a2f-c001-44b4-80d2-959ad2dc3b02.png)

**Comment by dakeXd** [comment]
Ahora no se puede rotar la pantalla :D.
Aparte, se reajusta el juego automáticamente al cambiar las dimensiones de la pantalla.
