### ISSUE TITLE
[USABILIDAD] Desbalanceo de enemigos en el juego.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#134]
**Prioridad**: Alto
**Plataforma o entorno:** PC, Chrome
**Descripción**: Hay enemigos muy fuertes, por lo que este tenga la probabilidad de aparecer en la 
primera sala es bastante injusta debido a que es bastante improbable que el jugador pueda derrotar 
a esos enemigos.
**Pasos para reproducirlo:** 
1. Entrar en partida. 
2. Avanzar a la primera sala. (Hay probabilidad de que no salga)

**Comment by dakeXd** [comment]
Reducida las estadísticas de la mayoría de enemigos, además, se ha pasado el daño mínimo a 1 para evitar que no sea imposible continuar
