### ISSUE TITLE
[PROGRAMACIÓN] El plátano te puede sacar del mapa con el empuje y te puede pegar a través de la pared.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#135]
**Prioridad**: Alto
**Plataforma o entorno:** PC, Chrome
**Descripción:** En algunas ocasiones dentro de partida, si dejas que el enemigo plátano te golpee 
contra alguna columna, este te puede permitir atravesar la columna y quedar situado fuera del 
mapa. 
**Pasos para reproducirlo:** 
1. Entrar en partida. 
2. Avanzar por las salas hasta encontrar un enemigo “plátano”. 
3. Colocarse en alguna posición cerca de una columna. 
4. Dejarse ser golpeado
![image](https://user-images.githubusercontent.com/72705329/143315838-c1f3b547-0efe-4cb3-b676-0532c51f0aaa.png)

**Comment by dakeXd** [comment]
Se ha evitado que los enemigos te puedan empujar fuera
