### ISSUE TITLE
[PROGRAMACIÓN] El juego en Google Chrome del móvil no funciona.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#136]
**Prioridad**: Crítico
**Plataforma o entorno:** Móvil, Chrome 
**Descripción:** Tras ejecutar el juego, si el jugador pulsa el botón de “Jugar”, el juego acaba 
congelándose solo y el navegador lanza un error.
**Pasos para reproducirlo:** 
1. Abrir el juego. 
2. Pulsar en el botón “Jugar”.

**Comment by dakeXd** [comment]
Se han comprimido los archivos del juego para que no se quede sin memoria en el navegador movil, solucionando este problema
