### ISSUE TITLE
[PROGRAMACIÓN] La pantalla no se adapta al tamaño de la venta del navegador.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#137]
**Prioridad**: Crítico
**Plataforma o entorno**: PC, Chrome/Firefox
**Descripción**: Al reescalar la pantalla, el canvas del juego no se reescala como es debido, quedando 
información del juego fuera de la ventana del navegador.
**Pasos para reproducirlo:**
1. Abrir el juego. 
2. Reescalar la ventana del navegador.

**Comment by dakeXd** [comment]
Ahora la pantalla se ajusta automaticamente
