### ISSUE TITLE
[CÓDIGO] Animaciones menú de ajustes

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#139]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟠Alto  
## Plataforma 
PC (Firefox y Chrome)
## Descripción
Si al abrir el menú de ajustes le das al botón de volver antes de que acabe su animación, se rompe la interfaz del menú
 ## Pasos para reproducirlo
Menú -> Ajustes -> Click en volver antes de que acabe la animación

**Comment by sourdonny** [comment]
Se ha implementado un sistema de corrutinas para que esto no suceda, hasta que las animaciones del menú no terminan, los botones no son interactuables.
