### ISSUE TITLE
[USABILIDAD] Volumen sfx de la lanza

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#145]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟢 Bajo 
## Plataforma 
Todas las plataformas
## Descripción
El volumen del sfx de la lanza a diferencia de los demás sfx está muy alto
 ## Pasos para reproducirlo
Menú -> Jugar ->  Encontrar y usar una lanza

**Comment by sourdonny** [comment]
El volumen de los efectos del juego ya se puede subir o bajar a gusto del jugador.
