### ISSUE TITLE
[CÓDIGO] Disparos enemigo cerebro

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#147]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟡 Medio
## Plataforma 
PC (Firefox y Chrome)
## Descripción
Cuando matas al enemigo cerebro, este dispara una bala más aunque ya no aparezca su sprite
 ## Pasos para reproducirlo
Menú -> Jugar ->  Encontrar un enemigo cerebro -> matarlo

**Comment by dakeXd** [comment]
Ya no puede disparar tras morir
