### ISSUE TITLE
[CÓDIGO] Música del menú sin repetición

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#148]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟡 Medio
## Plataforma 
PC (Firefox y Chrome)
## Descripción
La música del menú al acabar no se repite
 ## Pasos para reproducirlo
Menú inicial -> Esperar a que acabe la canción

**Comment by dakeXd** [comment]
Añadida musica en bucle
