### ISSUE TITLE
[CÓDIGO] Invencibilidad si te encierran

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#149]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
PC (Firefox y Chrome)
## Descripción
Si los enemigos de tipo esqueleto te encierran en una esquina y te dan un golpe, no te hacen más daño. Puede que sea porque las colisiones de daño funcionan con ""OnCollisionEnter"", como no sales de la colisión de daño te vuelves invencible
 ## Pasos para reproducirlo
Menú -> Jugar -> encontrar enemigos esqueleto y ponerte en una esquina. Dejar que te encierren y te ataquen.

**Comment by dakeXd** [comment]
Los enemigos ahora hacen daño mientras esten en contacto contigo en vez de al entrar en contacto contigo
