### ISSUE TITLE
[CÓDIGO] Iconos del menú principal se mantienen tras dar rápido a jugar.

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#152]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟢 Bajo 
## Plataforma 
Todas las plataformas
## Descripción
Si se pulsa el botón de jugar nada más aparece en pantalla los botones del menú principal no se actualizan y se quedan quietos.
 ## Pasos para reproducirlo
Menú -> dar click a jugar lo más rápido posible

![image](https://user-images.githubusercontent.com/43933908/143616214-ce673cdf-32f0-431a-ab4b-bb4420035838.png)

**Comment by sourdonny** [comment]
Se ha solucionado mediante corrutinas, no se pueden pulsar los botones hasta que las animaciones han terminado.
