### ISSUE TITLE
[COMPATIBILIDAD] Orientación de pantalla en móvil

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#153]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🔴 Crítico
## Plataforma 
Móvil (Firefox)
## Descripción
En cualquier escena, si comienzas el juego con orientación vertical y luego cambias a orientación horizontal, se rompe la resolución
 ## Pasos para reproducirlo
Abrir el juego en móvil con orientación vertical. En cualquier pantalla cambiar la orientación a horizontal

**Comment by dakeXd** [comment]
Pantalla reajustada autoamaticamente
