### ISSUE TITLE
[CÓDIGO] Los enemigos a veces no hacen daño

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#155]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
Todas las plataformas
## Descripción
Hay veces en las que si dos enemigos intentan dañar al jugador, el jugador deja de recibir daño pro dichos enemigos a veces.
 ## Pasos para reproducirlo
Menú -> Jugar -> Encontrarse con dos enemigos (por ejemplo los esqueletos) -> colisionar con ellos

![image](https://user-images.githubusercontent.com/43933908/143616250-cdaeabab-7ce4-4615-afe6-2f7119508c37.png)

**Comment by dakeXd** [comment]
Los enemigos ahora hacen daño mientras estes en contacto con ellos en vez de al chocar contra ellos
