### ISSUE TITLE
[CÓDIGO] Hay veces en las que las nubes pequeñas no llegan a tocar al jugador del todo y otras si.

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#158]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟡 Medio
## Plataforma 
Todas las plataformas
## Descripción
Las nubes pequeñas que persiguen al jugador no llegan a tocarle del todo unas veces y otras si. Parece que si que toca al jugador cuando una nueva nube se crea y por la colisión modifica la posición de otras nubes.
 ## Pasos para reproducirlo
Menú -> Jugar -> Enfrentarse al enemigo *Creador de nubes* y quedarse quieto.

![image](https://user-images.githubusercontent.com/43933908/143616298-40be472b-9fa9-42f0-a730-8aac265fd44f.png)

**Comment by dakeXd** [comment]
Reducido el tamaño de los agentes del navmesh, se acercaran mas a ti ahora
