### ISSUE TITLE
[USABILIDAD] Cuando se quita vida a los enemigos aparecen número negativos

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#160]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
Todas las plataformas
## Descripción
Hay enemigos (p.e el *Plátano*) que cuando reciben un ataque, salen números negativos, no sé sabe si eso significa que esta recibiendo daño o que -1 es porque la arma no es lo suficientemente fuerte.
 ## Pasos para reproducirlo
Menú -> Jugar -> Enfrentarse al plátano.

![image](https://user-images.githubusercontent.com/43933908/143616327-52b25821-2822-47e1-beca-f7b330fcf30c.png)

**Comment by dakeXd** [comment]
El daño minimo causado a pasado a ser 1
