### ISSUE TITLE
[CÓDIGO] La velocidad del juego se desajusta aveces cuando se reintenta

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#162]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
Todas las plataformas
## Descripción
Al dar a reintentar, hay veces que la velocidad del juego (quizás el timescale de Unity) se desajusta, y se mueve el personaje más lento. 
 ## Pasos para reproducirlo
Menú -> Jugar -> Reintentar

**Comment by dakeXd** [comment]
Las animaciones dependen de la velocidad del jugador, como al resetear el juego cambias de arma, cambia la velocidad de sus animaciones
