### ISSUE TITLE
[CÓDIGO] Objetos no se borran al cerrar el menu de objetos

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#163]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
Todas las plataformas
## Descripción
Si se pulsa el botón de borrar objetos, se selecciona un objeto para borrar, y se cierra el menú, no se borra dicho objeto si no que se cambia.
 ## Pasos para reproducirlo
Menú -> Jugar -> Pulsar un objeto con la opción de borrado, Pulsar Q nada más seleccionar el objeto para borrar.

**Comment by dakeXd** [comment]
Los objetos se siguen eliminando aunque cierres el menu
