### ISSUE TITLE
[CÓDIGO] El enemigo  *Bote de sal* dispara una última vez estando muerto

### ISSUE THREAD

**Issue by PepePm** [salmorejogames/TalesoftheDumbgeon#165]
# Issue del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
Todas las plataformas
## Descripción
El enemigo *Bote de sal* dispara una última vez si se le derrota poco antes del siguiente timing del disparo
 ## Pasos para reproducirlo
Menú -> Jugar -> Encontrar enemigo bote de sal -> derrotarlo antes de que dispare

**Comment by dakeXd** [comment]
Ahora el "bote de sal" muere de verdad al morir
