### ISSUE TITLE
[CÓDIGO] Guía 

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#166]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
PC (Firefox y Chrome)
## Descripción
Si estando en el apartado de guía, se vuelve a seleccionar guía aparece un bug que no deja volver al menú principal puesto que cubre toda la pantalla
 ## Pasos para reproducirlo
Menu -> Guia -> Guia

**Comment by sourdonny** [comment]
Se ha solucionado con las corrutinas, el botón de guía ya no se queda atascado.
