### ISSUE TITLE
[USABILIDAD] Salir de la pantalla de créidtos

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#170]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟡 Medio
## Plataforma 
PC (Chrome
## Descripción
No existe un botón para salir de la pantalla de crédtios, quizás al jugador le resulte útil y cómodo tener uno.
 ## Pasos para reproducirlo
Menú -> Créditos

**Comment by dakeXd** [comment]
Agregado boton para saltar los creditos
