### ISSUE TITLE
[USABILIDAD] Estética de la barra del volumen no cuadra con el resto

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#171]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟡 Medio
## Plataforma 
Todas las plataformas
## Descripción
La estetíca del *Slider* del volumen es la estándar de Unity, no cuadra con el resto de arte y puede sacar al jugador de la inmersión en el juego.
 ## Pasos para reproducirlo
Menú -> Volumen

![image](https://user-images.githubusercontent.com/50403556/143617202-5f3cf261-fe6e-46bd-814f-300506c68fbe.png)

**Comment by sourdonny** [comment]
Se ha renovado la estética de la barra de volumen.
