### ISSUE TITLE
[CODIGO] Enemigo *bote de sal* no quita vida al jugador

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#173]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟠 Alto 
## Plataforma 
Todas las plataformas
## Descripción
El enemigo con aspecto de bote de sal puede golpear al jugador con las bolas moradas, pero la barra de vida no se modifica.
 ## Pasos para reproducirlo
Menú -> Jugar -> Enfrentarse al Enemigo *Bote de sal* -> dejar que la bala morada golpe.

![image](https://user-images.githubusercontent.com/50403556/143617238-937e12cd-0558-4a0d-891e-c214ffcf8cdc.png)

**Comment by dakeXd** [comment]
Actualizado el daño minino a 1, mejorado el manejo de la barra de vida
