### ISSUE TITLE
[USABILIDAD] Icono de Guía se mantiene tras dar a Jugar rápido

### ISSUE THREAD

**Issue by drowlerd** [salmorejogames/TalesoftheDumbgeon#177]
# *Issue* del Grupo D (YellowFall Games)
## Prioridad
🟢 Bajo 
## Plataforma 
Todas las plataformas
## Descripción
Si el botón de jugar se pulsa una vez aparece, el botón de guía no desaparece. quizás sea por que aparece más tarde que el resto.
 ## Pasos para reproducirlo
Menú -> Pulsar el botón de jugar rápido (poco después de que aparezca).

**Comment by sourdonny** [comment]
El error se ha solucionado utilizando corrutinas para los botones, hasta que la animación no ha terminado, estos no son interactuables.
