### ISSUE TITLE
Daño múltiple

### ISSUE THREAD

**Issue by julio-guillen** [salmorejogames/TalesoftheDumbgeon#197]
**Prioridad**
Media

**Plataforma**
PC (Firefox y Chrome)

**Descripción**
Si estás a la distancia adecuada, puedes realizar múltiple ataques o lograr que tu ataque realice varios golpes.

**Pasos para reproducirlo**
Atacar cerca del enemigo

![image](https://user-images.githubusercontent.com/25005788/145553059-c2113aae-bfb9-479c-abe7-71a046406177.png)

**Comment by dakeXd** [comment]
Los ataques solo hacen daño una vez
