### ISSUE TITLE
[USABILIDAD] Mezcla de idiomas 

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#80]
**Prioridad**. Bajo
**Plataforma o entorno**. PC/Móvil, Chrome/Firefox
**Descripción.** El texto del juego se encuentra en una mezcla de dos idiomas, español e inglés.
**Pasos para reproducirlo**. Hay diferentes menús dentro del juego en español, pero en los créditos se 
mezclan idiomas a la hora de clasificar los roles del equipo.

**Comment by sourdonny** [comment]
Todos los textos del juegos están en español.
