### ISSUE TITLE
[ESTÉTICA] Música sin bucle

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#81]
**Prioridad:** Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción:** La música del menú principal se reproduce una vez solo.
**Pasos para reproducirlo:** Inicias el juego y esperas a que se reproduzca la música, una vez se acaba 
la música, no se vuelve a reproducir.

**Comment by dakeXd** [comment]
Se ha activado el bucle de la música
