### ISSUE TITLE
[USABILIDAD] Objetos equipados en la HUD.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#83]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC, Firefox 
**Descripción**: Los elementos del inventario pierden su textura original y se ven siempre blancos una 
vez equipados. 
**Pasos para reproducirlo**: Debes obtener un objeto de armadura y equipártelo en tu inventario y se 
verá de color blanco.

**Comment by dakeXd** [comment]
Las texturas se aplican a los objetos de la UI
