### ISSUE TITLE
[USABILIDAD] Descripción del juego confusa.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#84]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC 
**Descripción:** En la descripción del juego en la página web hay palabras tachadas sin sentido y el uso 
de la negrita hace que se vea mal. 
**Pasos para reproducirlo**: Debes ir a la página web del juego y leer la descripción.

**Comment by dakeXd** [comment]
Actualizada descripción del juego
