### ISSUE TITLE
[USABILIDAD] Daño negativo de los enemigos y confuso.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#85]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC, Chrome/Firefox 
**Descripción**: Hay veces que puedes curar a los enemigos devolviéndole vida con un ataque y el 
número sale en un color diferente dependiendo del arma dando a entender que se aplica un efecto 
al enemigo, cosa que no ocurre. 
**Pasos para reproducirlo**: Atacar al enemigo con diferentes armas

**Comment by dakeXd** [comment]
El daño por debajo de 0 se muestra como 0. Se ha indicado que los colores corresponden a los atacos muy efectivos y poco efectivos en las descripciones del juego
