### ISSUE TITLE
[USABILIDAD] Controles mal explicados en la descripción.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#86]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC, Chrome/Firefox 
**Descripción**: Los controles están mal explicados en la descripción del juego, se indica que el ataque 
es con clic derecho y los hechizos con clic izquierdo cuando es al revés. 
**Pasos para reproducirlo:** Leer la descripción del juego y comparar las instrucciones con las de la 
guía del menú del propio juego.

**Comment by dakeXd** [comment]
Solucionado!
