### ISSUE TITLE
[ESTÉTICA] Fondo negro del menú incoherente.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#89]
**Prioridad:** Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción**: El menú principal tiene un fondo negro que no concuerda con la estética del juego 
**Pasos para reproducirlo**: Iniciar el juego en el menú principal

**Comment by dakeXd** [comment]
Fondo del menu actualizado
