### ISSUE TITLE
[PROGRAMACIÓN] Slider de la música no ajustado.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#90]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC/Móvil, Chrome/Firefox 
**Descripción**: El slider de la música deja de funcionar una vez supera la mitad haciendo que el nivel 
máximo de la música sea la mitad del slider. 
**Pasos para reproducirlo**: Iniciar el juego y manipular el slider de la música de ajustes

**Comment by sourdonny** [comment]
Se ha subido el mínimo del slider para que no esté tan bajo nada más llegar a la mitad de su valor.
