### ISSUE TITLE
[PROGRAMACIÓN] Sobreposición de menús.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#93]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC, Chrome/Firefox 
**Descripción:** Puedes llegar a sobreponer el menú de ajustes sobre el menú de pausa. 
**Pasos para reproducirlo**: Pulsa el menú de pausa, seleccionas ajustes y pulsas escape para volver a 
ajustes.

**Comment by sourdonny** [comment]
Se ha implementado sistema de corrutinas para impedir esto, hasta que las animaciones de los botones no terminan los botones no son interactuables.
