### ISSUE TITLE
[ESTÉTICA] Bloques sin texturizar.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#95]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC/Móvil, Chrome/Firefox 
**Descripción:** Hay bloques sin texturizar por algunas caras dando la sensación errónea de la posición 
en la que se encuentran. 
**Pasos para reproducirlo:** Iniciar una partida y observar los bloques de los límites del mapa.

**Comment by dakeXd** [comment]
Los bloques se confundian con el fondo al tener el mismo color. Se ha actualizado el fondo, solventando este error
