### ISSUE TITLE
[ESTÉTICA] Pasar de sala sin animación.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#96]
**Prioridad**: Bajo 
**Plataforma o entorno**: PC/Móvil, Chrome/Firefox 
**Descripción**: El jugador pasa de una sala a otra sin una animación de movimiento y deslizándose 
por el suelo. 
**Pasos para reproducirlo**: Avanzar hacia otra sala en una partida.

**Comment by dakeXd** [comment]
Animacion activada durante el movimiento del personaje
