### ISSUE TITLE
[ESTÉTICA] Estética incoherente.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#98]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC/Móvil, Chrome/Firefox 
**Descripción**: La estética planteada en el menú principal choca de manera de manera negativa con 
el resto de la estética usada en el reto del juego. 
**Pasos para reproducirlo:** Comparar la estética del menú principal con la del resto del juego.

**Comment by sourdonny** [comment]
Se ha cambiado la estética del menú principal para que pegue más con el resto del juego.
