### ISSUE TITLE
[USABILIDAD] Botones de salir.

### ISSUE THREAD

**Issue by rox06io** [salmorejogames/TalesoftheDumbgeon#99]
**Prioridad**: Bajo 
**Plataforma o entorno:** PC/Móvil, Chrome/Firefox 
**Descripción:** Los botones de salir del juego te vuelven a la introducción del juego en vez del menú 
principal, haciendo que tengas que ver la animación siempre. 
**Pasos para reproducirlo:** Pulsar el botón de salir en una partida.

**Comment by sourdonny** [comment]
Los botones de salir te llevan al menú principal.
